from Student import Student
s = Student()
s.setid(100)
s.setname('Mohit Bhavsar')
s.setaddress('Ranip,Ahmedabad')
s.setmarks(89)
print('Student Id =',s.getid())
print('Student Name =',s.getname())
print('Student Addresss =',s.getaddress())
print('Student Marks =',s.getmarks())
